# Generated by Django 3.2.8 on 2021-10-31 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.tree')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tree',
            constraint=models.UniqueConstraint(fields=('user', 'slug'), name='user-tree-unique'),
        ),
    ]
